# 🐳 Universal Docker Compose Configuration
version: '3.8'

services:
  # Production service (Frontend + Backend in same container)
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DEPLOYMENT_TYPE: production
        FRONTEND_PORT: ${FRONTEND_PORT:-3000}
        API_SERVER_PORT: ${API_SERVER_PORT:-3001}
    restart: unless-stopped
    ports:
      - "${FRONTEND_PORT:-3000}:${FRONTEND_PORT:-3000}"  # Frontend port
      - "${API_SERVER_PORT:-3001}:${API_SERVER_PORT:-3001}"   # Backend API port (optional, nginx handles routing)
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - FRONTEND_PORT=${FRONTEND_PORT:-3000}
      - API_SERVER_PORT=${API_SERVER_PORT:-3001}
      - VITE_API_URL=${VITE_API_URL:-/api}
      - DB_HOST=${DB_HOST:-localhost}
      - DB_PORT=${DB_PORT:-3306}
      - DB_USER=${DB_USER:-admin}
      - DB_PASSWORD=${DB_PASSWORD:-secure_password}
      - DB_NAME=${DB_NAME:-myNGO}
      - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET:-your-super-secret-jwt-key-change-this-in-production}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET:-your-super-secret-refresh-key-change-this-in-production}
    stop_grace_period: 1m
    stop_signal: SIGTERM
    healthcheck:
      test: 
        - "CMD"
        - "sh"
        - "-c"
        - "wget --no-verbose --tries=1 --spider http://localhost:${FRONTEND_PORT:-3000}/ && wget --no-verbose --tries=1 --spider http://localhost:${API_SERVER_PORT:-3001}/health"
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

  # Development service
  dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    restart: unless-stopped
    ports:
      - "${DEV_PORT:-5173}:5173"
      - "${API_SERVER_PORT:-3001}:${API_SERVER_PORT:-3001}"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=${VITE_API_URL:-http://localhost:3001/api}
      - API_SERVER_PORT=${API_SERVER_PORT:-3001}
      - DB_HOST=${DB_HOST:-localhost}
      - DB_PORT=${DB_PORT:-3306}
      - DB_USER=${DB_USER:-admin}
      - DB_PASSWORD=${DB_PASSWORD:-secure_password}
      - DB_NAME=${DB_NAME:-myNGO}
      - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET:-your-super-secret-jwt-key-change-this-in-production}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET:-your-super-secret-refresh-key-change-this-in-production}
    command: ["pnpm", "run", "dev"]
    profiles:
      - dev

volumes:
  node_modules:
    driver: local 