# 🐳 Frontend-only Docker Compose Configuration
# Optimized for local development and testing
version: '3.8'

services:
  # Production service (main)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - NODE_ENV=production
      - VITE_API_URL=${VITE_API_URL:-https://api.example.com}
      - VITE_ENVIRONMENT=${VITE_ENVIRONMENT:-production}
      - VITE_APP_NAME=${VITE_APP_NAME:-myNGO}
      - VITE_APP_URL=${VITE_APP_URL:-https://app.example.com}
      - VITE_DEFAULT_FROM_EMAIL=${VITE_DEFAULT_FROM_EMAIL:-no-reply@example.com}
      - VITE_UMAMI_WEBSITE_ID=${VITE_UMAMI_WEBSITE_ID:-}
      - VITE_UMAMI_URL=${VITE_UMAMI_URL:-}
      - VITE_PLUNK_API_KEY=${VITE_PLUNK_API_KEY:-}
      - VITE_MAILJET_API_KEY=${VITE_MAILJET_API_KEY:-}
    stop_grace_period: 30s
    stop_signal: SIGTERM
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Development service
  dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    restart: unless-stopped
    ports:
      - "${DEV_PORT:-5173}:5173"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=${VITE_API_URL:-http://localhost:3002}
      - VITE_ENVIRONMENT=development
    command: ["pnpm", "run", "dev:frontend"]
    profiles:
      - dev

volumes:
  node_modules:
    driver: local 