# 🐳 Universal Docker Compose Configuration
version: '3.8'

services:
  # Production service with nginx (default)
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DEPLOYMENT_TYPE: production
    restart: unless-stopped
    ports:
      - "${WEB_PORT:-3100}:3100"
    volumes:
      - web_data:/usr/share/nginx/html
    environment:
      - NODE_ENV=production
      - API_URL=${API_URL:-http://localhost:3002}
    stop_grace_period: 1m
    stop_signal: SIGTERM
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3100/"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s

  # Simple server (for Coolify, Vercel, Railway, etc.)
  web-simple:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DEPLOYMENT_TYPE: simple
    restart: unless-stopped
    ports:
      - "${SIMPLE_PORT:-3000}:3000"
    environment:
      - NODE_ENV=production
      - API_URL=${API_URL:-http://localhost:3002}
    stop_grace_period: 1m
    stop_signal: SIGTERM
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  # Development service
  dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    restart: unless-stopped
    ports:
      - "${DEV_PORT:-5173}:5173"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - API_URL=${API_URL:-http://localhost:3002}
    command: ["pnpm", "run", "dev:frontend"]
    profiles:
      - dev

volumes:
  web_data:
    driver: local
  node_modules:
    driver: local 